data:
  class_path: dataset.LatentDataModule
  init_args:
    dataset_path: ./configs/protopnet/cub200/dataset.yml

trainer:
  devices: 1
  max_epochs: 10
  val_check_interval: 0.01
  accelerator: gpu
  precision: bf16-mixed
  gradient_clip_val: 1.0
  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: Val/Loss
        dirpath: ./logs/model/checkpoints
        filename: latentflow
        save_top_k: 1
        save_last: true
  logger:
    class_path: pytorch_lightning.loggers.TensorBoardLogger
    init_args:
      save_dir: ./logs/latentflow
      name: latentflow

model:
  decoder:
    class_path: modules.LatentDecoder # receives latent features 7x7x128 and outputs 224x224x64 z_{upsampled}
    init_args:
      input_dim: 256
      hidden_dim: 64 # iteratively decrease hidden dim
      output_dim: 64 # should be smaller
      strides: [2, 2, 2, 2, 2] # 7 * 2^5
      up_kernels: [3, 3, 3, 3, 3]
      n_convs: [2, 2, 2, 2, 2]
  flow_matcher: # UNet; 
    class_path: diffusion_model.FlowMatcher # TAKES {z_{upsampled} ; noisy x_{input}, "velocity t"} -> generates appropiate image & "velocity field t-1"
    # consider: larger decoder, simpler flow matcher
    # stride 2 -> 1 ???

    init_args:
      upsample_dim: 64
      hidden_dim: 64
      output_dim: 3
      strides: [1, 1, 1, 2]
      n_convs: [4, 4, 4, 4]
      sigma_min: 0.0001
  lr: 0.0001
